In [1]:
import numpy as np
import pandas as pd

In [2]:
df_train = pd.read_csv('C:/Users/Ax/Desktop/words/train.csv', encoding='utf-8')
df_train['id'] = df_train['id'].apply(str)

In [3]:
df_train.head()

,is_duplicate,qid1,qid2,question1,question2,id
0,1,Q397345,Q538594,W04465 W04058 W05284 W02916,W18238 W18843 W01490 W09905,0
1,0,Q193805,Q699273,W10054 W04476 W09996 W12244 W18103,W18439 W00863 W04259 W00740 W16070,1
2,0,Q085471,Q676160,W04346 W17378 W19355 W17926 W14185 W11567 W07863,W14586 W09745 W06017 W09067 W16319,2
3,0,Q189314,Q438123,W17508 W09996 W19662 W17534 W11399 W17057 W182...,W18238 W02357 W06606,3
4,0,Q267714,Q290126,W13157 W03390 W01952 W05789 W17378 W08714 W13157,W04476 W06606 W00316 W13157,4

In [4]:
df_test = pd.read_csv('C:/Users/Ax/Desktop/words/test.csv', encoding='utf-8')
df_test['test_id'] = df_test['test_id'].apply(str)

In [5]:
df_test.head()

,test_id,q1,q2,question1,question2
0,0,Q017571,Q006012,W17342 W06766 W04049 W16319 W07863,W11668 W17378 W11399 W14113
1,1,Q728241,Q542572,W17378 W17534 W02000 W19499 W05016 W06441 W193...,W10157 W13631 W11299 W07863
2,2,Q166997,Q118270,W17378 W19355 W03914 W18238 W03746,W19468 W10157 W02288 W18951 W18448
3,3,Q422420,Q514386,W16938 W17867 W18843 W01490 W06036,W01490 W00496
4,4,Q354329,Q032485,W17378 W19355 W01490 W11030 W19349 W18399 W03390,W04745 W04622 W00863 W16521 W17765 W06502 W18050

In [6]:
df_all = pd.concat((df_train, df_test),sort=True)
df_all['question1'].fillna('', inplace=True)
df_all['question2'].fillna('', inplace=True)

In [7]:
df_all

,id,is_duplicate,q1,q2,qid1,qid2,question1,question2,test_id
0,0,1.0,NaN,NaN,Q397345,Q538594,W04465 W04058 W05284 W02916,W18238 W18843 W01490 W09905,NaN
1,1,0.0,NaN,NaN,Q193805,Q699273,W10054 W04476 W09996 W12244 W18103,W18439 W00863 W04259 W00740 W16070,NaN
2,2,0.0,NaN,NaN,Q085471,Q676160,W04346 W17378 W19355 W17926 W14185 W11567 W07863,W14586 W09745 W06017 W09067 W16319,NaN
3,3,0.0,NaN,NaN,Q189314,Q438123,W17508 W09996 W19662 W17534 W11399 W17057 W182...,W18238 W02357 W06606,NaN
4,4,0.0,NaN,NaN,Q267714,Q290126,W13157 W03390 W01952 W05789 W17378 W08714 W13157,W04476 W06606 W00316 W13157,NaN
5,5,1.0,NaN,NaN,Q369715,Q658908,W12908 W19355 W08041 W06040 W18399 W01773 W16319,W12908 W06112 W08041 W17342,NaN
6,6,1.0,NaN,NaN,Q537991,Q268444,W16429 W14586 W03914 W09648 W02262 W18399 W06682,W13522 W05733 W17917 W10691 W16319,NaN
7,7,0.0,NaN,NaN,Q255847,Q179358,W14688 W13835 W03072 W05616,W03914 W02186 W08924 W13601 W18942 W05284 W083...,NaN
8,8,1.0,NaN,NaN,Q639518,Q053248,W04182 W05733 W03914 W09400 W13868,W04476 W11385 W05733 W18804 W16686 W19081 W18448,NaN
9,9,0.0,NaN,NaN,Q521550,Q435529,W14208 W14331 W06292 W15218 W01490 W17826 W188...,W02843 W07877 W03066 W05733 W20889 W09098,NaN
10,10,0.0,NaN,NaN,Q123362,Q056574,W05616 W08794 W13835 W08794 W12887 W02135 W04440,W06348 W16895 W19355 W02015 W18804 W05733 W079...,NaN
11,11,1.0,NaN,NaN,Q683881,Q087150,W17378 W14586 W01661 W03914 W04182 W12803 W02262,W07777 W05733 W04476 W11385 W10628 W08815 W047...,NaN
12,12,1.0,NaN,NaN,Q289444,Q505559,W18238 W08794 W16319 W01490 W02275 W18050 W101...,W05733 W07924 W08601 W03390 W06685 W01490 W163...,NaN
13,13,0.0,NaN,NaN,Q561541,Q435031,W17378 W19355 W20343 W19355 W10548 W19536 W098...,W12908 W16088 W06040,NaN
14,14,1.0,NaN,NaN,Q556979,Q613598,W12908 W19355 W08041 W08989 W16319,W16696 W11000 W13160 W01490 W02805 W19355 W08041,NaN
15,15,0.0,NaN,NaN,Q123788,Q114943,W15672 W17070 W18804 W05733 W03390 W16319 W07863,W04476 W10157 W02665 W17566 W07127 W12968 W154...,NaN
16,16,1.0,NaN,NaN,Q561061,Q196182,W18238 W17378 W19355 W13522 W05733 W06424,W17378 W06112 W05733 W18238 W18399 W03390,NaN
17,17,0.0,NaN,NaN,Q083256,Q301164,W05482 W14017 W03073 W01884 W05199 W07863,W16870 W05370 W17378 W13240 W16319 W11561 W141...,NaN
18,18,1.0,NaN,NaN,Q202392,Q213913,W00863 W06036 W10628 W15672 W18448,W18339 W11651 W14103 W17706,NaN
19,19,1.0,NaN,NaN,Q162443,Q675902,W15481 W09745 W10938 W17057 W10411 W04928 W068...,W15481 W13514,NaN
20,20,0.0,NaN,NaN,Q190842,Q508060,W08818 W18370 W19662 W16173 W19355 W10548 W18802,W01986 W02563 W11383 W18804 W18238 W09011 W19355,NaN
21,21,0.0,NaN,NaN,Q052258,Q073713,W15860 W18238 W05284 W18103,W17815 W10783 W13626,NaN
22,22,0.0,NaN,NaN,Q050550,Q248983,W16870 W18207 W08026 W20187 W19355 W05258 W200...,W07710 W10157 W04184 W18468 W15976 W02199 W193...,NaN
23,23,1.0,NaN,NaN,Q505409,Q502374,W17378 W03049 W01490 W10157 W15481 W10092,W18570 W18238 W01490,NaN
24,24,1.0,NaN,NaN,Q269648,Q587303,W08601 W20188 W04745 W19355 W06036 W16319 W04864,W17378 W02385 W17926 W16233 W09565 W16319,NaN
25,25,1.0,NaN,NaN,Q429695,Q189985,W18238 W01756 W19355 W17057 W01756 W19355 W154...,W13850 W16870 W18369 W18050 W07863 W18399 W017...,NaN
26,26,0.0,NaN,NaN,Q261905,Q494045,W07780 W04918 W06099 W14586 W11804 W01490 W182...,W01734 W00728 W07320 W18804 W10139 W03271 W19355,NaN
27,27,0.0,NaN,NaN,Q155492,Q713210,W11385 W06685 W01766 W02262 W15042,W17378 W17926 W05284 W02916 W16319 W16319 W07863,NaN
28,28,0.0,NaN,NaN,Q318473,Q046021,W02653 W10054 W18238 W12803 W13157,W04476 W03982 W02262 W19355 W18050 W03982 W052...,NaN
29,29,1.0,NaN,NaN,Q001264,Q069933,W08396 W09996 W01446,W04346 W18238 W09996 W04259 W18448 W17378 W141...,NaN
...,...,...,...,...,...,...,...,...,...
172926,NaN,NaN,Q323365,Q217646,NaN,NaN,W04346 W05284 W12244 W18050 W18802,W04182 W03914 W12803 W02262,172926
172927,NaN,NaN,Q188773,Q716118,NaN,NaN,W18238 W20709 W00391 W01892,W14103 W11322 W16657 W07863 W01952 W18103,172927
172928,NaN,NaN,Q051817,Q295642,NaN,NaN,W16696 W03213 W06194 W15203 W04874 W14075 W01490,W16696 W10633 W14713 W10411 W13466,172928
172929,NaN,NaN,Q236650,Q236416,NaN,NaN,W17378 W01490 W16319 W05284 W16070 W17378 W154...,W17378 W19355 W16481,172929
172930,NaN,NaN,Q025545,Q351262,NaN,NaN,W19169 W17781 W03472 W05733 W07863,W17378 W10157 W12908 W08041 W08496 W05733 W169...,172930
172931,NaN,NaN,Q721468,Q091552,NaN,NaN,W03746 W07924 W13160 W16319 W08238 W07863,W14392 W07924 W17978 W08794,172931
172932,NaN,NaN,Q188702,Q189232,NaN,NaN,W03249 W19637 W18238 W13686 W20889,W17378 W17534 W18934 W16319,172932
172933,NaN,NaN,Q639479,Q620869,NaN,NaN,W18238 W05284 W18050,W15481 W00997 W19355 W18804 W00564 W10938 W18103,172933
172934,NaN,NaN,Q554319,Q023537,NaN,NaN,W18482 W00722 W15131 W11723 W08986,W19593 W00931,172934
172935,NaN,NaN,Q388951,Q613631,NaN,NaN,W05733 W04259 W03472 W16938 W20171 W09996 W07863,W17378 W18238 W17765 W13895 W04259 W20487,172935
172936,NaN,NaN,Q638458,Q045913,NaN,NaN,W04075 W08041 W11299,W17378 W16070 W19355 W18804 W16696 W20101 W01490,172936
172937,NaN,NaN,Q384050,Q337419,NaN,NaN,W04346 W09745 W18804 W16870 W13631 W11299 W07863,W02896 W18238 W04465 W17378 W19355 W04259,172937
172938,NaN,NaN,Q329169,Q445396,NaN,NaN,W10588 W02556 W04745 W14103 W17706 W18103,W17378 W05284 W08276 W07903 W09745 W18238 W116...,172938
172939,NaN,NaN,Q354091,Q275771,NaN,NaN,W19098 W09745 W04885 W18399 W03472 W17926 W20024,W02262 W16319 W13396 W03472 W15218 W08986 W117...,172939
172940,NaN,NaN,Q124543,Q435887,NaN,NaN,W11385 W02385 W08410 W05490 W12244,W00740 W08276 W11668 W00454 W19499 W17057 W173...,172940
172941,NaN,NaN,Q545471,Q342986,NaN,NaN,W17378 W03472 W16895 W00564,W17378 W17534 W02000 W19499 W08276 W02262 W00564,172941
172942,NaN,NaN,Q072220,Q416033,NaN,NaN,W18238 W18843 W03746 W08238 W03286 W16319,W17378 W14113 W03746 W03390 W16319 W07863,172942
172943,NaN,NaN,Q707366,Q065578,NaN,NaN,W19536 W17945 W15481 W16696 W10633,W09326 W06763 W04839 W04965 W02240 W09414 W122...,172943
172944,NaN,NaN,Q540741,Q610575,NaN,NaN,W05733 W04745 W16705 W17057 W11385 W06685 W025...,W17378 W03104 W06250 W19355,172944
172945,NaN,NaN,Q709962,Q404086,NaN,NaN,W01749 W00863 W06099 W07278 W16319 W08276 W131...,W17378 W08986 W04476 W12803 W02262,172945
172946,NaN,NaN,Q170964,Q406354,NaN,NaN,W12440 W11299,W18612 W05016 W07863,172946
172947,NaN,NaN,Q592238,Q118907,NaN,NaN,W05607 W14713 W12803 W01490 W18238 W02552,W18238 W18843 W17378 W19355 W12908 W08041,172947
172948,NaN,NaN,Q353043,Q161920,NaN,NaN,W06702 W00564 W06036 W03472 W02262 W08238,W07278 W16173 W08636 W16319 W18802,172948
172949,NaN,NaN,Q618415,Q609736,NaN,NaN,W18804 W16173 W12908 W17508 W19355 W08410 W20024,W04476 W01490 W16319,172949
172950,NaN,NaN,Q633262,Q395475,NaN,NaN,W17378 W17534 W02000 W19499 W15481 W16319 W089...,W06112 W16870 W06112 W18238 W04745 W18399 W046...,172950
172951,NaN,NaN,Q162590,Q689256,NaN,NaN,W18417 W18804 W00863 W00796,W17378 W03746 W08238 W02149 W19355 W08041 W177...,172951
172952,NaN,NaN,Q651787,Q062309,NaN,NaN,W04346 W11140 W19136 W18804 W00863 W00796,W01661 W03914 W11285 W11140 W19136 W18399 W062...,172952
172953,NaN,NaN,Q339524,Q339349,NaN,NaN,W04346 W05016 W04745 W16564 W14103 W17706 W20487,W04346 W17378 W19355 W05733 W00863 W16521 W047...,172953
172954,NaN,NaN,Q355938,Q190839,NaN,NaN,W17378 W17534 W02021 W15484,W04075 W12908 W19355 W20171,172954
172955,NaN,NaN,Q189513,Q686712,NaN,NaN,W02385 W08276 W10311 W03914 W20024,W10139 W09602 W05284 W02090 W04058,172955

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
import itertools

In [9]:
counts_vectorizer = CountVectorizer(max_features=10000-1).fit(
    itertools.chain(df_all['question1'], df_all['question2']))
other_index = len(counts_vectorizer.vocabulary_)

In [10]:
counts_vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=9999, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [11]:
import re
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [12]:
words_tokenizer = re.compile(counts_vectorizer.token_pattern)

In [14]:
def create_padded_seqs(texts, max_len=20):
    seqs = texts.apply(lambda s: 
        [counts_vectorizer.vocabulary_[w] if w in counts_vectorizer.vocabulary_ else other_index
         for w in words_tokenizer.findall(s.lower())])
    return pad_sequences(seqs, maxlen=max_len)

In [15]:
#df_all = df_all.sample(1000) # Just for debugging

In [16]:
X1_train, X1_val, X2_train, X2_val, y_train, y_val = \
    train_test_split(create_padded_seqs(df_all[df_all['id'].notnull()]['question1']), 
                     create_padded_seqs(df_all[df_all['id'].notnull()]['question2']),
                     df_all[df_all['id'].notnull()]['is_duplicate'].values,
                     stratify=df_all[df_all['id'].notnull()]['is_duplicate'].values,
                     test_size=0.1)

In [17]:
import keras.layers as lyr
from keras.models import Model

In [18]:
input1_tensor = lyr.Input(X1_train.shape[1:])
input2_tensor = lyr.Input(X2_train.shape[1:])

words_embedding_layer = lyr.Embedding(X1_train.max() + 1, 300)
seq_embedding_layer = lyr.LSTM(256, activation='tanh')

seq_embedding = lambda tensor: seq_embedding_layer(words_embedding_layer(tensor))

merge_layer = lyr.multiply([seq_embedding(input1_tensor), seq_embedding(input2_tensor)])

dense1_layer = lyr.Dense(16, activation='sigmoid')(merge_layer)
ouput_layer = lyr.Dense(1, activation='sigmoid')(dense1_layer)

model = Model([input1_tensor, input2_tensor], ouput_layer)

model.compile(loss='binary_crossentropy', optimizer='adam')
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_1 (InputLayer)            (None, 20)           0
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 20)           0
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, 20, 300)      3000000     input_1[0][0]
                                                                 input_2[0][0]
__________________________________________________________________________________________________
lstm_1 (LSTM)                   (None, 256)          570368      embedding_1[0][0]
                                                                 embedding_1[1][0]
__________________________________________________________________________________________________
multiply_1 (Multiply)           (None, 256)          0           lstm_1[0][0]
                                                                 lstm_1[1][0]
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 16)           4112        multiply_1[0][0]
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 1)            17          dense_1[0][0]
==================================================================================================
Total params: 3,574,497
Trainable params: 3,574,497
Non-trainable params: 0
__________________________________________________________________________________________________

In [ ]:
model.fit([X1_train, X2_train], y_train, 
          validation_data=([X1_val, X2_val], y_val), 
          batch_size=64, epochs=10, verbose=2)

Train on 228947 samples, validate on 25439 samples
Epoch 1/10
 - 177s - loss: 0.4609 - val_loss: 0.3827
Epoch 2/10

In [ ]:
features_model = Model([input1_tensor, input2_tensor], merge_layer)
features_model.compile(loss='mse', optimizer='adam')

In [ ]:
F_train = features_model.predict([X1_train, X2_train], batch_size=32)
F_val = features_model.predict([X1_val, X2_val], batch_size=32)

In [ ]:
import xgboost as xgb

In [ ]:
dTrain = xgb.DMatrix(F_train, label=y_train)
dVal = xgb.DMatrix(F_val, label=y_val)

In [ ]:
xgb_params = {
    'objective': 'binary:logistic',
    'booster': 'gbtree',
    'eval_metric': 'logloss',
    'eta': 0.1, 
    'max_depth': 30,
    'subsample': 0.9,
    'colsample_bytree': 1 / F_train.shape[1]**0.5,
    'min_child_weight': 5,
    'silent': 1
}
bst = xgb.train(xgb_params, dTrain, 1000,  [(dTrain,'train'), (dVal,'val')], 
                verbose_eval=20, early_stopping_rounds=20)

In [ ]:
X1_test = create_padded_seqs(df_all[df_all['test_id'].notnull()]['question1'])
X2_test = create_padded_seqs(df_all[df_all['test_id'].notnull()]['question2'])

In [ ]:
F_test = features_model.predict([X1_test, X2_test], batch_size=32)

In [ ]:
dTest = xgb.DMatrix(F_test)

In [ ]:
df_sub = pd.DataFrame({
        'test_id': df_all[df_all['test_id'].notnull()]['test_id'].values,
        'y_pre': bst.predict(dTest, ntree_limit=bst.best_ntree_limit)
    }).set_index('test_id')

In [ ]:
df_sub.head()

In [ ]:
df_sub['y_pre'].hist(bins=100)

In [ ]:
df_sub.to_csv('submission20180624LSTM_07.csv', index=False)